name: kmutnb_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  location: ^4.3.0
  google_maps_flutter: ^2.0.9
  geolocator: ^7.7.1
  #provider: ^6.0.1
  url_launcher: ^6.0.10
  http: ^0.13.3
  flutter_rating_bar: ^4.0.0
  syncfusion_flutter_pdfviewer: ^19.3.54-beta
  firebase_core: ^1.10.0
  font_awesome_flutter: ^9.2.0
  google_sign_in: ^5.1.0
  firebase_auth: ^3.2.0
  get: ^4.3.8
  provider: ^4.3.2+2
  rflutter_alert: ^2.0.4
  firebase_database: ^8.1.0
  firebase_storage: ^10.1.0
  path_provider: ^2.0.4
  geocoding: ^2.0.1
  flutter_local_notifications: ^9.1.5
  firebase_messaging: ^11.2.3
  firebase_analytics: ^9.0.3
  file_picker: ^4.2.7
  flutter_launcher_icons: ^0.9.2
  image_picker: ^0.8.4+1
  intl: ^0.17.0
  #network_image_to_byte: ^0.0.1
  webview_flutter: ^2.0.13
  sign_button: ^2.0.2
  flutter_easyloading: ^3.0.3
  flutter_spinkit: ^5.1.0
  advance_pdf_viewer: ^2.0.0
  #google_fonts: ^2.3.0
  
  #firebase_storage: ^10.1.0
  #firebase_database: ^8.1.0

  #path_provider: ^2.0.4
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_app.png"
